version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apache_php
    platform: linux/amd64
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    platform: linux/amd64
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: stud
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql_db
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: stud
      MYSQL_DATABASE: autoservisas
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sqldump/autoservisas.sql:/docker-entrypoint-initdb.d/autoservisas.sql

volumes:
  db_data:
